## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default
tf.enable_eager_execution()

### Collect Data

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('/content/drive/My Drive/R6/prices.csv')

### Check all columns in the dataset

In [6]:
data.head()

                  date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

### Drop columns `date` and  `symbol`

In [0]:
data = data.drop(['date','symbol'],axis=1)

In [8]:
data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [9]:
data.shape

(851264, 5)

In [0]:
data = data.iloc[:1000]

In [12]:
data

           open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
5    115.510002  115.550003  114.500000  116.059998   1098000.0
6    116.459999  112.849998  112.589996  117.070000    949600.0
7    113.510002  114.379997  110.050003  115.029999    785300.0
8    113.330002  112.529999  111.919998  114.879997   1093700.0
9    113.660004  110.379997  109.870003  115.870003   1523500.0
10   109.059998  109.300003  108.320000  111.599998   1653900.0
11   109.730003  110.000000  108.320000  110.580002    944300.0
12   111.879997  111.949997  110.190002  112.949997    744900.0
13   111.320000  110.120003  110.000000  114.629997    703800.0
14   110.419998  111.000000  107.300003  111.400002    563100.0
15   110.769997  110.709999  109.019997  112.570000    896100.0
16   110.900002  112.580002  109.900002  112.970001    680400.0
17   113.349998  114.470001  111.669998  114.589996    749900.0
18   114.000000  114.500000  112.900002  114.849998    574200.0
19   113.250000  110.559998  109.750000  113.860001    694800.0
20   113.379997  114.050003  109.639999  114.639999    896300.0
21   114.080002  115.709999  114.080002  116.320000    956300.0
22   115.120003  114.019997  109.709999  116.489998    997100.0
23   113.300003  111.160004  110.459999  113.300003   1200500.0
24   111.169998  110.650002  109.639999  112.110001   1725200.0
25   106.730003  107.519997  106.360001  112.110001   1946000.0
26   105.629997  107.129997  104.110001  109.260002   1319500.0
27   108.559998  107.839996  107.070000  109.430000    922400.0
28   109.110001  110.769997  107.010002  111.300003   1185100.0
29   110.830002  111.239998  107.970001  112.110001    921500.0
..          ...         ...         ...         ...         ...
970   19.240000   18.680000   18.530001   19.430000   9097500.0
971   20.520000   20.290001   19.709999   20.549999   2242100.0
972   12.950000   13.550000   12.720000   13.600000   6205100.0
973   76.059998   75.440002   75.349998   76.370003    864600.0
974   19.620001   19.830000   19.480000   19.830000    709200.0
975   88.000000   87.370003   87.139999   88.239998   1129600.0
976   31.010000   30.959999   30.700001   31.120001   3449300.0
977   35.900002   35.189999   34.930000   35.910000   7517100.0
978   76.620003   77.650002   76.550003   77.790001   2356500.0
979   25.799999   26.420000   25.719999   26.610001   4839200.0
980   30.370001   31.059999   30.309999   31.110001   3684600.0
981   23.120001   22.920000   22.740000   23.129999  14428400.0
982   39.790001   39.610001   39.090000   39.799999   1463300.0
983   24.669997   25.140004   24.669997   25.160000    749600.0
984   11.250000   11.770000   11.200000   11.790000  13355100.0
985    1.630000    1.650000    1.600000    1.660000  11538300.0
986   17.020000   16.860001   16.790001   17.209999   9931300.0
987  257.840004  256.079998  253.050003  257.959995  12906000.0
988   48.099998   48.150002   47.700001   48.369999    369900.0
989   34.529999   34.430000   34.080002   34.750000   2701000.0
990   27.570000   27.790001   27.370000   27.919999   2627800.0
991   14.200000   14.420000   14.120000   14.430000   3258700.0
992   19.900000   19.580000   19.330000   20.059999   5206100.0
993   62.660000   62.299999   62.189999   62.750000   7099000.0
994   29.219999   28.719999   28.629999   29.309999   7795500.0
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
target = data['volume']
feature = data.drop(['volume'],axis=1)

In [0]:
x_train , x_test , y_train , y_test = train_test_split(feature, target, test_size = 0.2,random_state =7)

#### Convert Training and Test Data to numpy float32 arrays

In [0]:
import numpy as np
x_train = np.asarray(x_train).astype('float32')

In [0]:
x_test = np.array(x_test).astype('float32')

In [0]:
y_train = np.array(y_train).astype('float32')

In [0]:
y_test = np.array(y_test).astype('float32')

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
from sklearn.preprocessing import Normalizer
# from sklearn import preprocessing
transformer = Normalizer()

x_train= transformer.transform(x_train)
x_test= transformer.transform(x_test)

In [23]:
x_train

array([[0.49873042, 0.5009242 , 0.49385527, 0.5064088 ],
       [0.49924964, 0.50368565, 0.49219242, 0.50477445],
       [0.5000853 , 0.50262463, 0.49324548, 0.5039762 ],
       ...,
       [0.5001929 , 0.49977148, 0.4976645 , 0.50236005],
       [0.50253594, 0.49852157, 0.496339  , 0.50257486],
       [0.5012146 , 0.49876764, 0.49595365, 0.50402856]], dtype=float32)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
W = tf.random_normal(shape=[4,1])
b = tf.zeros(shape=[1])

In [26]:
W.numpy()

array([[-1.3827509],
       [-1.0280485],
       [-0.0399912],
       [-1.5159489]], dtype=float32)

2.Define a function to calculate prediction

In [0]:
def predection(x,W,b):
  return tf.add(tf.matmul(x_train,W),b)

3.Loss (Cost) Function [Mean square error]

In [30]:
def loss(x,y,W,b):
  return tf.reduce_mean(tf.square(y_train-predection(x,W,b))

SyntaxError: ignored

In [123]:
loss

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [0]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [128]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:x_train, y_:y_train})
    
    if epoch % 5 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

ValueError: ignored

### Get the shapes and values of W and b

### Model Prediction on 1st Examples in Test Dataset

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

### Splitting the data into feature set and target set

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

### Model Training

### Model Prediction

### Save the Model

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?